Updates

diff --git a/bin/caap-prior-extraction-simulation-analyze-statistics b/bin/caap-prior-extraction-simulation-analyze-statistics
--- a/bin/caap-prior-extraction-simulation-analyze-statistics
+++ b/bin/caap-prior-extraction-simulation-analyze-statistics
@@ -28,6 +28,38 @@ fi
 
 
 # 
+# Check input dirs (function)
+# 
+check_input_dirs() 
+{
+    if [[ ! -d "$simulated_dir" ]]; then
+        echo "Error! Simulated data directory \"$simulated_dir\" was not found!"
+        exit 1
+    fi
+    if [[ ! -d "$recovered_dir" ]]; then
+        echo "Error! Simulated data directory \"$recovered_dir\" was not found!"
+        exit 1
+    fi
+    if [[ ! -d "$simulated_dir/$image_name" ]]; then
+        echo "Error! Simulated data directory \"$simulated_dir/$image_name\" was not found!"
+        exit 1
+    fi
+    if [[ ! -d "$recovered_dir/$image_name" ]]; then
+        echo "Error! Simulated data directory \"$recovered_dir/$image_name\" was not found!"
+        exit 1
+    fi
+    if [[ ! -f "$simulated_dir/$image_name/datatable_Simulated.txt" ]]; then
+        echo "Error! Simulated data file \"$simulated_dir/$image_name/datatable_Simulated.txt\" was not found!"
+        exit 1
+    fi
+    if [[ ! -f "$recovered_dir/$image_name/datatable_Recovered_galfit.txt" ]]; then
+        echo "Error! Simulated data file \"$recovered_dir/$image_name/datatable_Recovered_galfit.txt\" was not found!"
+        exit 1
+    fi
+}
+
+
+# 
 # Read input arguments
 # 
 image_name=$(basename $(pwd -P))
@@ -36,6 +68,7 @@ recovered_dir="../../Recovered"
 output_dir="check_simulated_and_recovered_statistics"
 input_sbeam=()
 input_pbeam=()
+input_overwrite=0
 input_yes=0
 
 while [[ "$#" -gt 0 ]]; do
@@ -61,6 +94,7 @@ while [[ "$#" -gt 0 ]]; do
              "-fov") CAAP_CMD_TEXT="$1"; shift; CAAP_CMD_TYPE="input_pbeam";;
                "-s") CAAP_CMD_TEXT="$1"; shift; CAAP_CMD_TYPE="input_sbeam";;
                "-p") CAAP_CMD_TEXT="$1"; shift; CAAP_CMD_TYPE="input_pbeam";;
+       "-overwrite") CAAP_CMD_TEXT="$1";        CAAP_CMD_TYPE="overwrite";;
              "-yes") CAAP_CMD_TEXT="$1";        CAAP_CMD_TYPE="yes";;
     esac
     #echo $CAAP_CMD_TYPE
@@ -71,6 +105,7 @@ while [[ "$#" -gt 0 ]]; do
              "output_dir") if [[ $# -gt 0 ]]; then output_dir="$1"; fi;;
             "input_sbeam") if [[ $# -gt 0 ]]; then input_sbeam+=("$1"); fi;;
             "input_pbeam") if [[ $# -gt 0 ]]; then input_pbeam+=("$1"); fi;;
+              "overwrite")                         input_overwrite=1;;
                     "yes")                         input_yes=1;;
     esac
     #
@@ -82,9 +117,17 @@ done
 # Check sbeam pbeam
 # 
 if [[ ${#input_sbeam[@]} -eq 0 ]] || [[ ${#input_pbeam[@]} -eq 0 ]]; then
-    echo "Usage: "
-    echo "  caap-prior-extraction-simulation-analyze-statistics -synthesized-beam 0.1 0.1 -primary-beam 17"
-    echo ""
+    if [[ -f "$output_dir/info_primary_beam.txt" ]] && [[ -f "$output_dir/info_synthesized_beam.txt" ]]; then
+        echo "Warning! No primary beam nor synthesized beam was given, but found \"info_primary_beam.txt\" and \"info_synthesized_beam.txt\" under output directory \"$output_dir/\". Will load from those files."
+        echo ""
+        input_pbeam=($(cat "$output_dir/info_primary_beam.txt"))
+        input_sbeam=($(cat "$output_dir/info_synthesized_beam.txt"))
+    else
+        echo "Usage: "
+        echo "  caap-prior-extraction-simulation-analyze-statistics -synthesized-beam 0.1 0.1 -primary-beam 17"
+        echo ""
+        exit
+    fi
 else
     if [[ ${#input_sbeam[@]} -eq 1 ]]; then
         input_sbeam+=("${input_sbeam[0]}")
@@ -92,35 +135,6 @@ else
     if [[ ${#input_pbeam[@]} -eq 1 ]]; then
         input_pbeam+=("${input_pbeam[0]}")
     fi
-fi
-
-
-# 
-# Check input dirs
-# 
-if [[ ! -d "$simulated_dir" ]]; then
-    echo "Error! Simulated data directory \"$simulated_dir\" was not found!"
-    exit 1
-fi
-if [[ ! -d "$recovered_dir" ]]; then
-    echo "Error! Simulated data directory \"$recovered_dir\" was not found!"
-    exit 1
-fi
-if [[ ! -d "$simulated_dir/$image_name" ]]; then
-    echo "Error! Simulated data directory \"$simulated_dir/$image_name\" was not found!"
-    exit 1
-fi
-if [[ ! -d "$recovered_dir/$image_name" ]]; then
-    echo "Error! Simulated data directory \"$recovered_dir/$image_name\" was not found!"
-    exit 1
-fi
-if [[ ! -f "$simulated_dir/$image_name/datatable_Simulated.txt" ]]; then
-    echo "Error! Simulated data file \"$simulated_dir/$image_name/datatable_Simulated.txt\" was not found!"
-    exit 1
-fi
-if [[ ! -f "$recovered_dir/$image_name/datatable_Recovered_galfit.txt" ]]; then
-    echo "Error! Simulated data file \"$recovered_dir/$image_name/datatable_Recovered_galfit.txt\" was not found!"
-    exit 1
 fi
 
 
@@ -148,14 +162,21 @@ cp "$copy_macro_dir/"* "$output_dir/"
 # 
 # Run
 # 
-cat "$simulated_dir/$image_name/datatable_Simulated.txt"        | grep -v "^#$" > "$output_dir/datatable_Simulated.txt"
-cat "$recovered_dir/$image_name/datatable_Recovered_galfit.txt" | grep -v "^#$" > "$output_dir/datatable_Recovered_galfit.txt"
+if [[ $input_overwrite -eq 1 ]] || [[ ! -f "$output_dir/datatable_Simulated.txt" ]];        then check_input_dirs; cat "$simulated_dir/$image_name/datatable_Simulated.txt"        | grep -v "^#$" > "$output_dir/datatable_Simulated.txt"; fi
+if [[ $input_overwrite -eq 1 ]] || [[ ! -f "$output_dir/datatable_Recovered_galfit.txt" ]]; then check_input_dirs; cat "$recovered_dir/$image_name/datatable_Recovered_galfit.txt" | grep -v "^#$" > "$output_dir/datatable_Recovered_galfit.txt"; fi
 
 cd "$output_dir"
 echo "${input_pbeam[@]}" > "info_primary_beam.txt"
 echo "${input_sbeam[@]}" > "info_synthesized_beam.txt"
-echo "macro read a_dzliu_code_check_simulated_and_recovered.sm go" | sm
+
+if [[ $input_overwrite -eq 1 ]] || [[ ! -f "simu_data_input.txt" ]]; then
+    echo "macro read a_dzliu_code_check_simulated_and_recovered.sm go" | sm
+fi
+
 echo "macro read a_dzliu_code_analyze_statistics.sm analyze_statistics" | sm
+rm sim_diagram_output_v*/*.{eps,pdfmarks,pdfconverts}
+rm aaa_*.{eps,pdfmarks,pdfconverts}
+
 echo "Done!"
 
 
